### ISSUE TITLE
Wdk

### ISSUE THREAD

**Issue by ddkwork** [saferwall/winsdk2json#10]
Can you support wdk and ewdk?

**Comment by LordNoteworthy** [comment]
What do you mean by `suppr` ?

**Comment by ddkwork** [comment]
> What do you mean by `suppr` ?

https://learn.microsoft.com/zh-cn/windows-hardware/drivers/download-the-wdk

**Comment by ddkwork** [comment]
![{F0D2B4A6-0BF0-4634-9A89-C59755B93C32}](https://github.com/saferwall/winsdk2json/assets/19886504/25f8c8f6-8994-49e9-ba92-e3d40e20ed82)

**Comment by ddkwork** [comment]
> What do you mean by `suppr` ?

Sorry my input app has a bug, my
 Means is support.
